version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: tasks-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: tasks_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser -d tasks_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: tasks-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE: postgresql://taskuser:taskpass@db:5432/tasks_db
      PORT: 80
      NODE_ENV: production
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  postgres_data:

